@echo off
echo Downloading Go...
curl.exe -L -o ..\go.zip https://go.dev/dl/go1.22.0.windows-amd64.zip
echo Extracting Go...
powershell -Command "Expand-Archive -Path '..\go.zip' -DestinationPath '..\go_dist' -Force"
echo Setting PATH...
set PATH=%CD%\..\go_dist\go\bin;%PATH%
echo Testing Go...
go version
echo Pushing Prisma...
call npx prisma db push
echo Tidying Go...
go mod tidy
echo Starting Server...
go run cmd\api\main.go
