/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PageIdRouteImport } from './routes/page.$id'
import { Route as VerifyIdRouteImport } from './routes/verify.$id'
import { Route as WorkspaceIdRouteImport } from './routes/workspace.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PageIdRoute = PageIdRouteImport.update({
  id: '/page/$id',
  path: '/page/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIdRoute = VerifyIdRouteImport.update({
  id: '/verify/$id',
  path: '/verify/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdRoute = WorkspaceIdRouteImport.update({
  id: '/workspace/$id',
  path: '/workspace/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/page/$id': typeof PageIdRoute
  '/verify/$id': typeof VerifyIdRoute
  '/workspace/$id': typeof WorkspaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/page/$id': typeof PageIdRoute
  '/verify/$id': typeof VerifyIdRoute
  '/workspace/$id': typeof WorkspaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/page/$id': typeof PageIdRoute
  '/verify/$id': typeof VerifyIdRoute
  '/workspace/$id': typeof WorkspaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/auth'
    | '/dashboard'
    | '/pricing'
    | '/page/$id'
    | '/verify/$id'
    | '/workspace/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/auth'
    | '/dashboard'
    | '/pricing'
    | '/page/$id'
    | '/verify/$id'
    | '/workspace/$id'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/auth'
    | '/dashboard'
    | '/pricing'
    | '/page/$id'
    | '/verify/$id'
    | '/workspace/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  PricingRoute: typeof PricingRoute
  PageIdRoute: typeof PageIdRoute
  VerifyIdRoute: typeof VerifyIdRoute
  WorkspaceIdRoute: typeof WorkspaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/$id': {
      id: '/page/$id'
      path: '/page/$id'
      fullPath: '/page/$id'
      preLoaderRoute: typeof PageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$id': {
      id: '/verify/$id'
      path: '/verify/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$id': {
      id: '/workspace/$id'
      path: '/workspace/$id'
      fullPath: '/workspace/$id'
      preLoaderRoute: typeof WorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  PricingRoute: PricingRoute,
  PageIdRoute: PageIdRoute,
  VerifyIdRoute: VerifyIdRoute,
  WorkspaceIdRoute: WorkspaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
